#### Reshaping arrays

In [1]:
import numpy as np

In [7]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 2., 6., 8.],
       [8., 4., 0., 7.],
       [8., 2., 6., 7.]])

In [9]:
a.shape

(3, 4)

In [12]:
b=a.ravel()
b

array([8., 2., 6., 8., 8., 4., 0., 7., 8., 2., 6., 7.])

In [16]:
b.shape

(12,)

In [17]:
a.shape

(3, 4)

In [18]:
a.T

array([[8., 8., 8.],
       [2., 4., 2.],
       [6., 0., 6.],
       [8., 7., 7.]])

In [19]:
a.T.shape

(4, 3)

In [20]:
a.shape

(3, 4)

In [23]:
a.reshape(2,6)

array([[8., 2., 6., 8., 8., 4.],
       [0., 7., 8., 2., 6., 7.]])

In [24]:
a.shape


(3, 4)

In [25]:
a.resize(2,6)

In [26]:
a.shape

(2, 6)

In [27]:
a

array([[8., 2., 6., 8., 8., 4.],
       [0., 7., 8., 2., 6., 7.]])

In [29]:
a.reshape(3,4)

array([[8., 2., 6., 8.],
       [8., 4., 0., 7.],
       [8., 2., 6., 7.]])

In [30]:
a.shape

(2, 6)

#### Stacking arrays

In [31]:
a = np.floor(10*np.random.random((2,2)))

In [32]:
a


array([[6., 6.],
       [6., 1.]])

In [33]:
b = np.floor(10*np.random.random((2,2)))

In [34]:
b

array([[5., 8.],
       [7., 2.]])

In [36]:
np.vstack((a,b))

array([[6., 6.],
       [6., 1.],
       [5., 8.],
       [7., 2.]])

In [37]:
a.shape

(2, 2)

In [38]:
np.hstack((a,b))

array([[6., 6., 5., 8.],
       [6., 1., 7., 2.]])

In [39]:
c = np.hstack((a,b))
c

array([[6., 6., 5., 8.],
       [6., 1., 7., 2.]])

In [40]:
a.shape


(2, 2)

In [41]:
np.column_stack((a,b))

array([[6., 6., 5., 8.],
       [6., 1., 7., 2.]])

In [42]:
np.row_stack((a,b))

array([[6., 6.],
       [6., 1.],
       [5., 8.],
       [7., 2.]])

In [45]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays
d = np.array([2.,3.])
e = np.array([4.,5.])
np.column_stack((d,e))

array([[2., 4.],
       [3., 5.]])

In [48]:
np.hstack((d,e))

array([2., 3., 4., 5.])

In [47]:
#the function row_stack is equivalent to vstack for any input arrays. 
np.row_stack((d,e))

array([[2., 3.],
       [4., 5.]])

In [52]:
 from numpy import newaxis
d[:,newaxis]               # this allows to have a 2D columns vector

array([[2.],
       [3.]])

In [53]:
np.column_stack((d[:,newaxis],e[:,newaxis]))

array([[2., 4.],
       [3., 5.]])

In [54]:
np.row_stack((d[:,newaxis],e[:,newaxis]))

array([[2.],
       [3.],
       [4.],
       [5.]])

In [56]:
np.r_[1:5,0,4]


array([1, 2, 3, 4, 0, 4])

In [60]:
np.c_[1:4]

array([[1],
       [2],
       [3]])

In [61]:
np.concatenate((d,e))

array([2., 3., 4., 5.])

#### Splitting one array into several smaller ones

In [62]:
 a = np.floor(10*np.random.random((2,12)))

In [63]:
a

array([[1., 6., 1., 6., 3., 8., 9., 0., 8., 5., 2., 5.],
       [0., 7., 3., 0., 5., 9., 8., 0., 3., 3., 1., 3.]])

In [64]:
np.hsplit(a,3)   # Split a into 3

[array([[1., 6., 1., 6.],
        [0., 7., 3., 0.]]), array([[3., 8., 9., 0.],
        [5., 9., 8., 0.]]), array([[8., 5., 2., 5.],
        [3., 3., 1., 3.]])]

In [65]:
f=np.hsplit(a,3)

In [67]:
f[0]

array([[1., 6., 1., 6.],
       [0., 7., 3., 0.]])

In [68]:
f[1]

array([[3., 8., 9., 0.],
       [5., 9., 8., 0.]])

In [70]:
f[0][0]

array([1., 6., 1., 6.])

In [71]:
f[0][0][0]

1.0

In [72]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[1., 6., 1.],
        [0., 7., 3.]]), array([[6.],
        [0.]]), array([[3., 8., 9., 0., 8., 5., 2., 5.],
        [5., 9., 8., 0., 3., 3., 1., 3.]])]

In [73]:
g= np.hsplit(a,(3,4)) 

In [75]:
g[0]


array([[1., 6., 1.],
       [0., 7., 3.]])

In [76]:
data=np.arange(6).reshape((3,2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
 np.average(range(1,5),weights=range(4,0,-1))

2.0

In [96]:
a=np.array([-1.7, -1.3, -0.2,0.2,1.2,1.75,1.7,2.3])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  1.,  2.])

In [98]:
np.sum([[1,2],[3,4]], axis=0)

array([4, 6])

In [104]:
np.sum([[1,5],[3,4]], axis=1)

array([6, 7])

### Copies and Views

#####  No copy at all   
Simple assignments make no copy of array objects or of their data.

In [165]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [166]:
b = a[::2]
b


array([ 0,  2,  4,  6,  8, 10])

In [167]:
a is b # a and b are two names for the same ndarray object

False

In [168]:
b=a
a is b

True

In [169]:
 b.shape = 3,4    # changes the shape of a

In [170]:
a.shape


(3, 4)

Python passes mutable objects as references, so function calls make no copy.

In [171]:
def f(x):
    print(id(x))


In [172]:
id(a) # id is a unique identifier of an object

1307149805568

In [173]:
f(b)

1307149805568


#### View or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [174]:
c = a.view()

In [175]:
c is a 

False

In [176]:
c.base is a # c is a view of the data owned by a

True

In [177]:
c.flags.owndata

False

In [178]:
c.shape = 6,2

In [179]:
a.shape # a's shape doesn't change

(3, 4)

In [180]:
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [181]:
 c[0,1] = 1234                      # a's data changes

In [182]:
c

array([[   0, 1234],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9],
       [  10,   11]])

In [183]:
a

array([[   0, 1234,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [188]:
s = a[ : , 1:3]
s

array([[1234,    2],
       [   5,    6],
       [   9,   10]])

In [189]:
s[:]

array([[1234,    2],
       [   5,    6],
       [   9,   10]])

In [190]:
s[:]=10

In [191]:
s[:]

array([[10, 10],
       [10, 10],
       [10, 10]])

In [192]:
s=10

In [193]:
s

10

In [194]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

#### Deep copy

In [195]:
d = a.copy()                          # a new array object with new data is created

In [196]:
d is a

False

In [197]:
d.base is a                           # d doesn't share anything with a

False

In [198]:
d[0,0] = 9999

In [199]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])