#### Reshaping arrays

In [2]:
import numpy as np

In [3]:
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 4., 5., 3.],
       [6., 9., 0., 6.],
       [8., 6., 8., 1.]])

In [4]:
a.shape

(3, 4)

In [5]:
b=a.ravel()
b

array([7., 4., 5., 3., 6., 9., 0., 6., 8., 6., 8., 1.])

In [6]:
b.shape

(12,)

In [7]:
a.shape

(3, 4)

In [8]:
a.T

array([[7., 6., 8.],
       [4., 9., 6.],
       [5., 0., 8.],
       [3., 6., 1.]])

In [9]:
a.T.shape

(4, 3)

In [10]:
a.shape

(3, 4)

In [11]:
a.reshape(2,6)

array([[7., 4., 5., 3., 6., 9.],
       [0., 6., 8., 6., 8., 1.]])

In [12]:
a.shape


(3, 4)

In [13]:
a.resize(2,6)

In [14]:
a.shape

(2, 6)

In [15]:
a

array([[7., 4., 5., 3., 6., 9.],
       [0., 6., 8., 6., 8., 1.]])

In [16]:
a.reshape(3,4)

array([[7., 4., 5., 3.],
       [6., 9., 0., 6.],
       [8., 6., 8., 1.]])

In [17]:
a.shape

(2, 6)

#### Stacking arrays

In [18]:
a = np.floor(10*np.random.random((2,2)))

In [19]:
a


array([[7., 1.],
       [7., 4.]])

In [20]:
b = np.floor(10*np.random.random((2,2)))

In [21]:
b

array([[3., 0.],
       [9., 8.]])

In [22]:
np.vstack((a,b))

array([[7., 1.],
       [7., 4.],
       [3., 0.],
       [9., 8.]])

In [23]:
a.shape

(2, 2)

In [24]:
np.hstack((a,b))

array([[7., 1., 3., 0.],
       [7., 4., 9., 8.]])

In [25]:
c = np.hstack((a,b))
c

array([[7., 1., 3., 0.],
       [7., 4., 9., 8.]])

In [26]:
a.shape


(2, 2)

In [27]:
np.column_stack((a,b))

array([[7., 1., 3., 0.],
       [7., 4., 9., 8.]])

In [28]:
np.row_stack((a,b))

array([[7., 1.],
       [7., 4.],
       [3., 0.],
       [9., 8.]])

In [29]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays
d = np.array([2.,3.])
e = np.array([4.,5.])
np.column_stack((d,e))

array([[2., 4.],
       [3., 5.]])

In [30]:
np.hstack((d,e))

array([2., 3., 4., 5.])

In [31]:
#the function row_stack is equivalent to vstack for any input arrays. 
np.row_stack((d,e))

array([[2., 3.],
       [4., 5.]])

In [32]:
 from numpy import newaxis
d[:,newaxis]               # this allows to have a 2D columns vector

array([[2.],
       [3.]])

In [33]:
np.column_stack((d[:,newaxis],e[:,newaxis]))

array([[2., 4.],
       [3., 5.]])

In [34]:
np.row_stack((d[:,newaxis],e[:,newaxis]))

array([[2.],
       [3.],
       [4.],
       [5.]])

In [35]:
np.r_[1:5,0,4]


array([1, 2, 3, 4, 0, 4])

In [36]:
np.c_[1:4]

array([[1],
       [2],
       [3]])

In [37]:
np.concatenate((d,e))

array([2., 3., 4., 5.])

#### Splitting one array into several smaller ones

In [38]:
 a = np.floor(10*np.random.random((2,12)))

In [39]:
a

array([[9., 7., 2., 3., 8., 0., 5., 1., 7., 5., 7., 4.],
       [3., 3., 6., 0., 1., 7., 3., 8., 8., 6., 3., 7.]])

In [40]:
np.hsplit(a,3)   # Split a into 3

[array([[9., 7., 2., 3.],
        [3., 3., 6., 0.]]), array([[8., 0., 5., 1.],
        [1., 7., 3., 8.]]), array([[7., 5., 7., 4.],
        [8., 6., 3., 7.]])]

In [41]:
f=np.hsplit(a,3)

In [42]:
f[0]

array([[9., 7., 2., 3.],
       [3., 3., 6., 0.]])

In [43]:
f[1]

array([[8., 0., 5., 1.],
       [1., 7., 3., 8.]])

In [44]:
f[0][0]

array([9., 7., 2., 3.])

In [45]:
f[0][0][0]

9.0

In [46]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[9., 7., 2.],
        [3., 3., 6.]]), array([[3.],
        [0.]]), array([[8., 0., 5., 1., 7., 5., 7., 4.],
        [1., 7., 3., 8., 8., 6., 3., 7.]])]

In [47]:
g= np.hsplit(a,(3,4)) 

In [48]:
g[0]


array([[9., 7., 2.],
       [3., 3., 6.]])

In [49]:
data=np.arange(6).reshape((3,2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
 np.average(range(1,5),weights=range(4,0,-1))

2.0

In [51]:
a=np.array([-1.7, -1.3, -0.2,0.2,1.2,1.75,1.7,2.3])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  1.,  2.])

In [52]:
np.sum([[1,2],[3,4]], axis=0)

array([4, 6])

In [53]:
np.sum([[1,5],[3,4]], axis=1)

array([6, 7])

### Copies and Views

#####  No copy at all   
Simple assignments make no copy of array objects or of their data.

In [96]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
b = a[::2]
b


array([ 0,  2,  4,  6,  8, 10])

In [98]:
a is b # a and b are two names for the same ndarray object

False

In [99]:
b=a
a is b

True

In [100]:
 b.shape = 3,4    # changes the shape of a

In [101]:
a.shape


(3, 4)

Python passes mutable objects as references, so function calls make no copy.

In [102]:
def f(x):
    print(id(x))


In [103]:
id(a) # id is a unique identifier of an object

2974836268688

In [104]:
f(a)

2974836268688


#### View or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [105]:
c = a.view()

In [106]:
c is a 

False

In [107]:
c.base is a # c is a view of the data owned by a

True

In [108]:
c.flags.owndata

False

In [109]:
c.shape = 6,2

In [110]:
a.shape # a's shape doesn't change

(3, 4)

In [111]:
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [112]:
 c[0,1] = 1234                      # a's data changes

In [113]:
c

array([[   0, 1234],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9],
       [  10,   11]])

In [114]:
a

array([[   0, 1234,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [115]:
s = a[ : , 1:3]
s

array([[1234,    2],
       [   5,    6],
       [   9,   10]])

In [116]:
s[:]

array([[1234,    2],
       [   5,    6],
       [   9,   10]])

In [117]:
s[:]=10

In [118]:
s[:]

array([[10, 10],
       [10, 10],
       [10, 10]])

In [119]:
s=10

In [120]:
s

10

In [121]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

#### Deep copy

In [122]:
d = a.copy()                          # a new array object with new data is created

In [123]:
d is a

False

In [124]:
d.base is a                           # d doesn't share anything with a

False

In [125]:
d[0,0] = 9999

In [126]:
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

In [127]:
d

array([[9999,   10,   10,    3],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])