### Pandas Function Application


###### To apply your own or another library’s functions to Pandas objects, you should be aware of the three important methods. The appropriate method to use depends on whether your function expects to operate on an entire DataFrame, row- or column-wise, or element wise.

    1. Table wise Function Application: pipe()
    2. Row or Column Wise Function Application: apply()
    3. Element wise Function Application: applymap()

#####  Table-wise Function Application

Custom operations can be performed by passing the function and the appropriate number of parameters as pipe arguments. Thus, operation is performed on the whole DataFrame.

###### adder function

The adder function adds two numeric values as parameters and returns the sum.

In [23]:
import pandas as pd
import numpy as np

def adder(ele1,ele2):
    print("ele1: ", ele1)
    print("ele2: ", ele2)
    return ele1+ele2

r = np.random.randn(5,3)
print(r)
df = pd.DataFrame(r,columns=['col1','col2','col3'])
print(df)
print(df.pipe(adder,4))
print(df)
print(df.apply(np.mean))

[[ 0.47927305 -0.27683686  0.57574699]
 [-0.93305595 -0.01516465  0.13425567]
 [-0.99291131  0.271866   -1.14091165]
 [-1.18578136  1.11938374 -1.74944264]
 [ 0.8955763  -1.41439478 -1.20711814]]
       col1      col2      col3
0  0.479273 -0.276837  0.575747
1 -0.933056 -0.015165  0.134256
2 -0.992911  0.271866 -1.140912
3 -1.185781  1.119384 -1.749443
4  0.895576 -1.414395 -1.207118
ele1:         col1      col2      col3
0  0.479273 -0.276837  0.575747
1 -0.933056 -0.015165  0.134256
2 -0.992911  0.271866 -1.140912
3 -1.185781  1.119384 -1.749443
4  0.895576 -1.414395 -1.207118
ele2:  4
       col1      col2      col3
0  4.479273  3.723163  4.575747
1  3.066944  3.984835  4.134256
2  3.007089  4.271866  2.859088
3  2.814219  5.119384  2.250557
4  4.895576  2.585605  2.792882
       col1      col2      col3
0  0.479273 -0.276837  0.575747
1 -0.933056 -0.015165  0.134256
2 -0.992911  0.271866 -1.140912
3 -1.185781  1.119384 -1.749443
4  0.895576 -1.414395 -1.207118
col1   -0.347380
col

##### Row or Column Wise Function Application

Arbitrary functions can be applied along the axes of a DataFrame or Panel using the apply() method, which, like the descriptive statistics methods, takes an optional axis argument. By default, the operation performs column wise, taking each column as an array-like.

In [30]:
df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
print(df)
df.apply(np.mean)
print(df)
print (df.apply(np.mean))

       col1      col2      col3
0  1.305334  0.610330  0.753719
1  1.351581 -0.063001  0.988738
2  1.366740  1.247631  0.135441
3 -1.431409 -0.112658 -0.687645
4  0.458578 -0.608444 -0.787887
       col1      col2      col3
0  1.305334  0.610330  0.753719
1  1.351581 -0.063001  0.988738
2  1.366740  1.247631  0.135441
3 -1.431409 -0.112658 -0.687645
4  0.458578 -0.608444 -0.787887
col1    0.610165
col2    0.214772
col3    0.080473
dtype: float64


By passing axis parameter, operations can be performed row wise.

In [31]:
#df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
df.apply(np.mean,axis=1)
print (df.apply(np.mean,axis=1))



0    0.889794
1    0.759106
2    0.916604
3   -0.743904
4   -0.312584
dtype: float64


In [34]:
print(df.apply(np.mean))
print(df.apply(lambda x: x.max() - x.min()))

col1    0.610165
col2    0.214772
col3    0.080473
dtype: float64
col1    2.798149
col2    1.856075
col3    1.776625
dtype: float64


##### Element Wise Function Application

Methods applymap() on DataFrame and analogously map() on Series accept any Python function taking a single value and returning a single value.

In [39]:
print(df)
df['col1'].map(lambda x:x*100)
print(df)
print(df['col1'].map(lambda x:x*100))

df.applymap(lambda x:x*100)
print(df.applymap(lambda x:x*100))

       col1      col2      col3
0  1.305334  0.610330  0.753719
1  1.351581 -0.063001  0.988738
2  1.366740  1.247631  0.135441
3 -1.431409 -0.112658 -0.687645
4  0.458578 -0.608444 -0.787887
       col1      col2      col3
0  1.305334  0.610330  0.753719
1  1.351581 -0.063001  0.988738
2  1.366740  1.247631  0.135441
3 -1.431409 -0.112658 -0.687645
4  0.458578 -0.608444 -0.787887
0    130.533407
1    135.158073
2    136.673991
3   -143.140945
4     45.857812
Name: col1, dtype: float64
         col1        col2       col3
0  130.533407   61.033030  75.371855
1  135.158073   -6.300096  98.873762
2  136.673991  124.763145  13.544077
3 -143.140945  -11.265773 -68.764462
4   45.857812  -60.844354 -78.788711
